// server/src/api/modules/FinancialReport/FinancialReport.types.ts

// This interface defines the shape of the report data generated by the service.
export interface FinancialReport {
  description: string;
  category: string;
  amount: number;
  date: Date;
  type: "income" | "expense";
}

// This interface defines the overall structure of a report summary.
export interface ReportSummary {
  reportName: string;
  period: string;
  totalIncome: number;
  totalExpenses: number;
  netIncome: number;
  details: FinancialReport[];
}